version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: movie_reviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=vector

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/movie_reviews
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/movie_reviews
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: celery -A tasks worker --loglevel=info

volumes:
  postgres_data: 